### ISSUE TITLE
Create a data-driven `define-xml` from P21

### ISSUE THREAD

**Issue by kaz462** [pharmaverse/pharmaverseadam#3]
generate a blank data-driven `define-xml` along with the Excel spec, so that we can -
2023Q4
- apply variable labels

In the future:
- manually enter the derivation text for each variable 
- add a column for "admiral function" used in the `Variable` and `ValueLevel` sheets
- link some work from the following issue: https://github.com/pharmaverse/admiral/issues/688

**Comment by kaz462** [comment]
@dgrassellyb could you help sync the `pharmaverseadam` with the most recent admiral templates so that I can use the latest data for our Excel specification?

For testing purpose, I generated a blank excel spec through P21, some labels can be automatically populated, but still need some manual work:
[define-2023-11-22T16-49-51-709.xlsx](https://github.com/pharmaverse/pharmaverseadam/files/13454025/define-2023-11-22T16-49-51-709.xlsx)

* this spec is based on the `.rda` files under [data](https://github.com/pharmaverse/pharmaverseadam/tree/main/data) folder, except for `adpp` is generated from admiral templates [ad_adpp.R](https://github.com/pharmaverse/admiral/blob/main/inst/templates/ad_adpp.R) see https://github.com/pharmaverse/pharmaverseadam/issues/54

**Comment by dgrassellyb** [comment]
> @dgrassellyb could you help sync the `pharmaverseadam` with the most recent admiral templates so that I can use the latest data for our Excel specification?
> 
> For testing purpose, I generated a blank excel spec through P21, some labels can be automatically populated, but still need some manual work: [define-2023-11-22T16-49-51-709.xlsx](https://github.com/pharmaverse/pharmaverseadam/files/13454025/define-2023-11-22T16-49-51-709.xlsx)
> 
> * this spec is based on the `.rda` files under [data](https://github.com/pharmaverse/pharmaverseadam/tree/main/data) folder, except for `adpp` is generated from admiral templates [ad_adpp.R](https://github.com/pharmaverse/admiral/blob/main/inst/templates/ad_adpp.R) see [Clean up variable names: remove illegal characters #54](https://github.com/pharmaverse/pharmaverseadam/issues/54)

Hi @kaz462, I updated the data this week on this branch : https://github.com/pharmaverse/pharmaverseadam/tree/add_script (however some templates from admiralonco and admiralvaccine are not running - see issue #52 ) - especially admiralvaccine is quite outdated, for example still using `admiral.test` package

**Comment by kaz462** [comment]
@dgrassellyb @manciniedoardo I've uploaded the excel spec to google sheet:
https://docs.google.com/spreadsheets/d/1NSkOhT2uk-ZhQ5ZXthFVlxJ_NtljPWKzeGPJygxFI5s/edit#gid=1352706827
