### ISSUE TITLE
Bug: Some templates are not running

### ISSUE THREAD

**Issue by dgrassellyb** [pharmaverse/pharmaverseadam#52]
### What happened?

Just reporting issues running templates for admiral family packages : 

- admiralonco : 
ad_adrs_basic.R : 
```
Error in filter_joined(dataset, by_vars = subject_keys, order = order,  : 
  argument "dataset_add" is missing, with no default
Calls: %>% ... filter_joined -> assert_data_frame -> is.data.frame
In addition: Warning message:
The `filter` argument of `filter_joined()` is deprecated as of admiral 1.0.0.
ℹ Please use the `filter_join` argument instead.
ℹ The deprecated feature was likely used in the admiralonco package.
  Please report the issue at <https://github.com/pharmaverse/admiralonco/issues>. 
Execution halted
```
ad_adtr.R : 
```
Error in derive_vars_joined(., dataset_add = adtr_sum, by_vars = exprs(USUBJID),  : 
  argument "join_type" is missing, with no default
Calls: %>% ... derive_vars_joined -> get_joined_data -> assert_character_scalar
Execution halted
```

 - admiralvaccine : 
 ad_adce.R : 
 ```
 Error in derive_vars_joined(adce02, dataset_add = adperiods, by_vars = exprs(STUDYID,  : 
  argument "join_type" is missing, with no default
Calls: %>% ... der
```
ad_adface.R
 ```
 Error in derive_vars_joined(adface, dataset_add = period_ref, by_vars = exprs(STUDYID,  : 
  argument "join_type" is missing, with no default
Calls: %>% ... derive_vars_joined -> get_joined_data -> assert_character_scalar
Execution halted
```
- ad_adis.R
```
Error in derive_vars_joined(adis_crit, dataset_add = period_ref, by_vars = exprs(STUDYID,  : 
  argument "join_type" is missing, with no default
Calls: derive_var
```
- ad_adsl.R
```
Error in library(admiral.test) : 
  there is no package called ‘admiral.test’
Execution halted
```

(for some of them it seems just related to the use of deprecated functions and use of admiral.test that has been decommissioned )

**Comment by dgrassellyb** [comment]
@manciniedoardo : just tagging you here, if you want to test the run of the templates you can run `data-raw/create_adams_data.R` on this branch https://github.com/pharmaverse/pharmaverseadam/tree/add_script 
Note that you can also add `github_token.R` script under `data-raw` folder with the following code : 
`github_pat <- "<YOUR GITHUB PAT TOKEN"` (let me know if you need more instructions to create github access token)

**Comment by manciniedoardo** [comment]
thanks @dgrassellyb! I've tried to run the file - it fails at this step? 
![image](https://github.com/pharmaverse/pharmaverseadam/assets/53403957/3e225fb8-e4de-42af-88a5-0deff4a7b442)
