### ISSUE TITLE
ADaM BDS datasets non-compliance with the IG 

### ISSUE THREAD

**Issue by botsp** [pharmaverse/pharmaverseadam#58]
### Let us know where something needs a refresh or put your idea here!

Hi, 

I noticed that there are some records/values has non-compliance with the ADaM IG. Maybe I could record some issues and hope this would be useful for your work.

1. ADSL: The label of ADSL should be "Subject-Level Analysis Dataset", not "Demographics".
2. ADLB: PARAMCD in ("BASO", “LYMPH”）has two corresponding PARAM values.
3. ADPC: ATPT="Pre-dose" assigned 3 different values of ATPTN(-0.5,24,48).

**Comment by kaz462** [comment]
Hi @botsp thanks for your feedback! 
> 1. ADSL: The label of ADSL should be "Subject-Level Analysis Dataset", not "Demographics".

@dgrassellyb  @pharmaverse/admiraldata for 1, maybe we can populate dataset labels in [adams-specs.xlsx](https://github.com/pharmaverse/pharmaverseadam/blob/main/inst/extdata/adams-specs.xlsx) and add [`xportr::xportr_df_label`](https://atorus-research.github.io/xportr/reference/xportr_df_label.html) in [`create_adams_data.R`](https://github.com/pharmaverse/pharmaverseadam/blob/main/data-raw/create_adams_data.R) to reset dataset-level labels, does anyone have bandwidth to work on this?

For 2, 3, we will look into them and update accordingly in the following weeks.

**Comment by manciniedoardo** [comment]
> @dgrassellyb @pharmaverse/admiraldata for 1, maybe we can populate dataset labels in [adams-specs.xlsx](https://github.com/pharmaverse/pharmaverseadam/blob/main/inst/extdata/adams-specs.xlsx) and add [`xportr::xportr_df_label`](https://atorus-research.github.io/xportr/reference/xportr_df_label.html) in [`create_adams_data.R`](https://github.com/pharmaverse/pharmaverseadam/blob/main/data-raw/create_adams_data.R) to reset dataset-level labels, does anyone have bandwidth to work on this?

@kaz462 this seems like a good first issue for some of our new joiners?

**Comment by dgrassellyb** [comment]
Hi @manciniedoardo / @kaz462 : not a lot of bandwidth to work on this this week, maybe it could be a good first issue as @manciniedoardo says for new comers ?

**Comment by kaz462** [comment]
closing this issue as dataset label was added - https://github.com/pharmaverse/pharmaverseadam/commit/f56d83bb7aefd0ab0b416134abc0a514e4106158
