### ISSUE TITLE
Documentation:  Could we get some Dataset Labels on the Help Pages?

### ISSUE THREAD

**Issue by bms63** [pharmaverse/pharmaverseadam#68]
### Please select a category the issue is focused on?

Function Documentation

### Let us know where something needs a refresh or put your idea here!

![image](https://github.com/pharmaverse/pharmaverseadam/assets/10111024/5b20bfef-c693-427c-b11d-28944ce81de5)

**Comment by sadchla-codes** [comment]
@bms63 We can do this in #64
