### ISSUE TITLE
General Issue: Remove non-ASCII characters in the package ahead of any release

### ISSUE THREAD

**Issue by manciniedoardo** [pharmaverse/pharmaverseadam#71]
### Background Information

Non-ASCII characters cause NOTES to appear when running pre-release checks. We should remove any from the package to avoid any issues.

### Definition of Done

- Run the following in the searchbar on github:
 `repo:pharmaverse/pharmaverseadam /[^\x00-\x7F]+/`
- Remove anything flagged.

**Comment by sadchla-codes** [comment]
Hi @manciniedoardo  below is the result from running ``repo:pharmaverse/pharmaverseadam /[^\x00-\x7F]+/``
do you want the following that are circle in red to be removed?
![image](https://github.com/pharmaverse/pharmaverseadam/assets/112789549/194b9d84-e8ee-4287-bd62-7be573cef414)

**Comment by manciniedoardo** [comment]
Yes please, to be safe let's remove the fistbumps and replace the quotes with normal quotes (""). That way we have no non ascii chars anywhere in the package.
