### ISSUE TITLE
[Feature Request] Missing variables in the ADCM dataset

### ISSUE THREAD

**Issue by edelarua** [pharmaverse/pharmaverseadam#77]
Hello,

While testing safety templates in scda.test, we found that the following variables are missing from the ADCM dataset:

- [x] pharmaverse/pharmaversesdtm#120
- [ ] ATIREL
- [ ] ATC1, ATC2, ATC3, ATC4

If you require any further details please let me/the SME team know. 

Thanks!!

**Comment by kaz462** [comment]
Hi @edelarua @manciniedoardo, 
- could you help suggest how to derive `ATC1/2/3/4` based on the following variables from current `cm`? 
```r
 [1] "STUDYID"  "DOMAIN"   "USUBJID"  "CMSEQ"    "CMSPID"   "CMTRT"    "CMDECOD"  "CMINDC"   "CMCLAS"  
[10] "CMDOSE"   "CMDOSU"   "CMDOSFRQ" "CMROUTE"  "VISITNUM" "VISIT"    "VISITDY"  "CMDTC"    "CMSTDTC" 
[19] "CMENDTC"  "CMSTDY"   "CMENDY" 
```
- Is "Adverse Event Treatment Relationship" the label for `ATIREL`?

Thanks!

**Comment by manciniedoardo** [comment]
@kaz462 I think the label for ATIREL should be "Time Relative to Reference"

**Comment by manciniedoardo** [comment]
For the first bullet point, let's bring up at today's admiral call.

**Comment by edelarua** [comment]
Hi @kaz462,

> * could you help suggest how to derive `ATC1/2/3/4` based on the following variables from current `cm`?
> 
> ```r
>  [1] "STUDYID"  "DOMAIN"   "USUBJID"  "CMSEQ"    "CMSPID"   "CMTRT"    "CMDECOD"  "CMINDC"   "CMCLAS"  
> [10] "CMDOSE"   "CMDOSU"   "CMDOSFRQ" "CMROUTE"  "VISITNUM" "VISIT"    "VISITDY"  "CMDTC"    "CMSTDTC" 
> [19] "CMENDTC"  "CMSTDY"   "CMENDY" 
> ```

The `ATC1/2/3/4` variables directly correlate with the `CMDECOD`/`CMCLAS` variables. For example, in `random.cdisc.data` we have the following synthetic data:

![Screenshot 2024-08-07 150043](https://github.com/user-attachments/assets/26dfdc42-01c1-419d-bf1e-e167a7d73657)

> * Is "Adverse Event Treatment Relationship" the label for `ATIREL`?

`ATIREL` in our `adcm` data has the label "Time Relation of Medication" with two levels - `CONCOMITANT` and `PRIOR`.

**Comment by kaz462** [comment]
@edelarua Thank you for clarification! I was thinking to get the real ATC code, but it seems you are okay with synthetic/fake data as long as the values populated correlate with `CMDECOD`/`CMCAT`?

@manciniedoardo maybe we can simply simulate the ATC variables instead of merging with whodrug/`facm` from [derive_vars_atc](https://pharmaverse.github.io/admiral/reference/derive_vars_atc.html) to avoid the complication, what do you think? 
copy @pharmaverse/admiral @pharmaverse/admiral_comm

**Comment by edelarua** [comment]
> @edelarua Thank you for clarification! I was thinking to get the real ATC code, but it seems you are okay with synthetic/fake data as long as the values populated correlate with `CMDECOD`/`CMCAT`?

For our purposes, that should be fine. 

Thanks!

**Comment by bms63** [comment]
> @edelarua Thank you for clarification! I was thinking to get the real ATC code, but it seems you are okay with synthetic/fake data as long as the values populated correlate with `CMDECOD`/`CMCAT`?
> 
> @manciniedoardo maybe we can simply simulate the ATC variables instead of merging with whodrug/`facm` from [derive_vars_atc](https://pharmaverse.github.io/admiral/reference/derive_vars_atc.html) to avoid the complication, what do you think? copy @pharmaverse/admiral @pharmaverse/admiral_comm

I'm okay with simulated data if it makes sense!  Can something simple be put together and we can discuss a little more?
