### ISSUE TITLE
Update readme to include extension packages 

### ISSUE THREAD

**Issue by kaz462** [pharmaverse/pharmaverseadam#8]
Does "{admiral} template" refer to the templates in admiral core only or does it include the templates in the extension packages {admiralonco}, {admiralophta}, {admiralvaccines}, ...?

If it includes extension packages, we may need to add something regarding the requirements for the CI/CD workflow to process them.

_Originally posted by @bundfussr in https://github.com/pharmaverse/pharmaverseadam/pull/6#discussion_r1311788501_

**Comment by manciniedoardo** [comment]
Extension package scripts are also included in pharmaverseadam (thanks, @dgrassellyb) so i will quickly update the readme to include this, and use this opportunity to also remove the tags ahead of release.
